domain:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/core-domain/**/*'
          - 'packages/sync-protocol/**/*'

pos-client:
  - changed-files:
      - any-glob-to-any-file: 'apps/pos-client/**/*'

web-dashboard:
  - changed-files:
      - any-glob-to-any-file: 'apps/web-dashboard/**/*'

marketing-site:
  - changed-files:
      - any-glob-to-any-file: 'apps/marketing-site/**/*'

edge-api:
  - changed-files:
      - any-glob-to-any-file: 'apps/edge-api/**/*'

ui-kit:
  - changed-files:
      - any-glob-to-any-file: 'packages/ui-kit/**/*'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**/*'
          - 'mise.toml'
