[package]
name = "pos-client-tauri"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
core-domain = { path = "../../../packages/core-domain" }
sync-protocol = { path = "../../../packages/sync-protocol" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[lints]
workspace = true
