[package]
name = "pos-client-tauri"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "pos_client_tauri_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }

[dependencies]
tokio = { workspace = true, features = ["net", "time", "rt", "macros", "io-util", "rt-multi-thread"] }
thiserror = { workspace = true }
tauri = { version = "2.0.0", features = [] }
rusqlite = { workspace = true }
core-domain = { path = "../../../packages/core-domain" }
sync-protocol = { path = "../../../packages/sync-protocol" }

serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
rust_decimal = { workspace = true }
reqwest = { version = "0.13.5", features = ["json"] }
tokio-util = { version = "0.7.19", features = ["rt"] }
async-trait = { workspace = true }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[lints]
workspace = true

[dev-dependencies]
sync-protocol = { path = "../../../packages/sync-protocol", features = ["test-helpers"] }
mockito = "1.7.2"
