[package]
name = "edge-api"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
worker = { version = "0.5", features = ["d1"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
core-domain = { path = "../../packages/core-domain" }
rust_decimal.workspace = true
chrono = { workspace = true, features = ["serde", "wasmbind"] }
uuid = { workspace = true, features = ["serde", "v4", "v7", "js"] }

[lints]
workspace = true
