[package]
name = "edge-api"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
worker = "0.5"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
core-domain = { path = "../../packages/core-domain" }

[lints]
workspace = true

[lints.rust]
unsafe_code = "deny"
