// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	HEARTH_SYNC_ROOM: DurableObjectNamespace /* HearthRoom */;
	CELLAR_DB: D1Database;
}
