// Generated by Wrangler by running \`wrangler types --env-interface CloudflareBindings\`

import type { DurableObjectNamespace, D1Database } from "@cloudflare/workers-types";

interface CloudflareBindings {
	HEARTH_SYNC_ROOM: DurableObjectNamespace /* HearthRoom */;
	CELLAR_DB: D1Database;
}
